-- AN EXPLORATORY DATA ANALYSIS PROJCTS
-- TABLE USED : ADD TITLE OF DATA SET
-- EXPLAIN THE USE OF THE PROJECT
-- EXPLAIN THE AIM OF THE PROJECTS

-- PROCESSES
-- STEP ONE: DATA CLEANING
SELECT *
FROM employee_demographics;

-- REMOVE DUPLICATES
-- REMOVE NULL VALUES
-- GROUP AGE OR LARGE VALUES
-- REMOVE UNWANTED COLUMNS




